# Generated by Django 3.2.6 on 2022-07-19 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quartos', '0001_initial'),
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hospedagem', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospedes.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quartos.quarto')),
            ],
        ),
    ]
