# Generated by Django 3.2.6 on 2022-07-21 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospedagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('P', 'Pago'), ('A', 'Aberto'), ('C', 'Cancelado')], max_length=1)),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospedagens.hospedagem')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumos.tipo_consumo')),
            ],
        ),
    ]
