# Generated by Django 3.2.6 on 2022-07-19 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Simples'), (2, 'Casal'), (3, 'Luxo')])),
                ('status', models.CharField(choices=[('O', 'Ocupado'), ('L', 'Livre'), ('R', 'Reservado')], max_length=1)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospedes.hospede')),
            ],
        ),
    ]
