# Generated by Django 3.2.6 on 2022-07-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0001_initial'),
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hospedes.hospede'),
        ),
    ]
