# Generated by Django 3.2.6 on 2022-07-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('quarto', models.IntegerField(choices=[(1, 'Simples'), (2, 'Casal'), (3, 'Luxo')])),
                ('cpf', models.CharField(max_length=11)),
                ('numero_cartao', models.CharField(max_length=50)),
                ('data_validade', models.DateField()),
                ('codigo_seguranca', models.CharField(max_length=3)),
            ],
        ),
    ]
