# Generated by Django 3.2.6 on 2022-07-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservar',
            new_name='Reserva',
        ),
    ]
